name: Shift Left N Secure PR Review
on:
  pull_request:
    types: [opened]
jobs:
  review_security_issues_and_bugs:
    runs-on: ubuntu-latest
    env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        GH_PR_NUMBER: ${{ github.event.pull_request.number }}
        GH_REPO: ${{ github.repository }}

    steps:
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: install shift-left-secure package
      run: |
          python -m pip install --upgrade pip
          pip install shift-left-secure
          
    - name: Review PR
      run: python -m shift_left_secure.gh_action
