name: Review PR 
on:
  pull_request:
    types: [opened]
jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
     - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

    - name: install shift-left-secure package
        run: |
          python -m pip install --upgrade pip
          pip install shift-left-secure

    - name: Review PR
      env:
        OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
      run: python -m shift_left_secure.action
